.trivy_config_secrets:
  image:
    name: $CI_REGISTRY/department-csec/secobserve/secobserve_gitlab_includes/secobserve_scanners:latest
  stage: test
  variables:
    FURTHER_PARAMETERS: ""
    TRIVY_NO_PROGRESS: "true"
    RUN_DIRECTORY: "."
    SO_UPLOAD: "true"
    SO_PARSER_NAME: "Sarif"
    SO_FILE_NAME: "$REPORT_NAME"
  script:
    - cd "$RUN_DIRECTORY"
    - trivy filesystem $FURTHER_PARAMETERS --exit-code 0 --format sarif --security-checks config,secret --output "$CI_PROJECT_DIR/$REPORT_NAME" "$TARGET"
    - cd "$CI_PROJECT_DIR"
    - >
      if [ "$SO_UPLOAD" == "true" ]; then
        file_upload_observations.sh
      fi
  interruptible: true
  allow_failure: true
  artifacts:
    when: always
    paths: 
      - "$REPORT_NAME"
