name: 'SecObserve OWASP ZAP'
description: 'Scans web sites and APIs with OWASP ZAP'
author: 'MaibornWolff'

inputs:
  target:
    description: 'The target to be scanned, here a URL.'
    required: true
    default: '.'
  report_name:
    description: 'The name of the report to be written.'
    required: true
  script:
    description: 'ZAP script to run.'
    required: false
    default: 'zap-baseline.py'
  further_parameters:
    description: 'Further parameters to be given to the scanner.'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'docker://stefanfle/secobserve-scanners:dev'
  entrypoint: '/entrypoints/entrypoint_owasp_zap.sh'
  env:
    TARGET: ${{ inputs.target }}
    REPORT_NAME: ${{ inputs.report_name }}
    SCRIPT: ${{ inputs.script }}
    FURTHER_PARAMETERS: ${{ inputs.further_parameters }}
