name: 'SecObserve Gitleaks'
description: 'Scans Python code for vulnerabilities with Gitleaks'
author: 'MaibornWolff'
inputs:
  report_name:
    description: 'The name of the report to be written.'
    required: true
  run_directory:
    description: 'The directory where to run the scanner.'
    required: false
    default: '.'
  further_parameters:
    description: 'Further parameters to be given to the scanner.'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'docker://stefanfle/secobserve-scanners:dev'
  entrypoint: '/entrypoints/entrypoint_gitleaks.sh'
  env:
    REPORT_NAME: ${{ inputs.report_name }}
    RUN_DIRECTORY: ${{ inputs.run_directory }}
    FURTHER_PARAMETERS: ${{ inputs.further_parameters }}
